/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohan
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtresult = new javax.swing.JTextField();
        jbtnpm = new javax.swing.JButton();
        jbtnslash = new javax.swing.JButton();
        jbtnce = new javax.swing.JButton();
        jbtnc = new javax.swing.JButton();
        jbtnbs = new javax.swing.JButton();
        jbtnstar = new javax.swing.JButton();
        jbtndig4 = new javax.swing.JButton();
        jbtndig7 = new javax.swing.JButton();
        jbtndig8 = new javax.swing.JButton();
        jbtndig9 = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtndig5 = new javax.swing.JButton();
        jbtndig6 = new javax.swing.JButton();
        jbtnminus = new javax.swing.JButton();
        jbtndig2 = new javax.swing.JButton();
        jbtndig3 = new javax.swing.JButton();
        jbtndig1 = new javax.swing.JButton();
        jbtndig0 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtresult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtresult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtresultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 50));

        jbtnpm.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnpm.setText("±");
        jbtnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpmActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 74, 60));

        jbtnslash.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnslash.setText("/");
        jbtnslash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnslashActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnslash, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 74, 60));

        jbtnce.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnce.setText("CE");
        jbtnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnceActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnce, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 74, 60));

        jbtnc.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnc.setText("C");
        jbtnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 74, 60));

        jbtnbs.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jbtnbs.setText("←");
        jbtnbs.setActionCommand("");
        jbtnbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 60));

        jbtnstar.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnstar.setText("*");
        jbtnstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnstarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnstar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 74, 60));

        jbtndig4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig4.setText("4");
        jbtndig4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 74, 60));

        jbtndig7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig7.setText("7");
        jbtndig7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 74, 60));

        jbtndig8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig8.setText("8");
        jbtndig8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 74, 60));

        jbtndig9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig9.setText("9");
        jbtndig9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 74, 60));

        jbtnplus.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 74, 60));

        jbtndig5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig5.setText("5");
        jbtndig5.setActionCommand("");
        jbtndig5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 74, 60));

        jbtndig6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig6.setText("6");
        jbtndig6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 74, 60));

        jbtnminus.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnminus.setText("-");
        jbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 74, 60));

        jbtndig2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig2.setText("2");
        jbtndig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 74, 60));

        jbtndig3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig3.setText("3");
        jbtndig3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 74, 60));

        jbtndig1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig1.setText("1");
        jbtndig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 74, 60));

        jbtndig0.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndig0.setText("0");
        jbtndig0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndig0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndig0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 74, 60));

        jbtndot.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 74, 60));

        jbtnequal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 74, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void EnterNumbers(String q){
        String Nums = jtxtresult.getText() + q;
        jtxtresult.setText(Nums);
    }
    private void jbtnslashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnslashActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "/";
    }//GEN-LAST:event_jbtnslashActionPerformed

    private void jbtnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpmActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtxtresult.getText()));
        nums = nums* (-1);
        jtxtresult.setText(String.valueOf(nums));
    }//GEN-LAST:event_jbtnpmActionPerformed

    private void jbtnbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbsActionPerformed
        String backsp = null;
        
        if(jtxtresult.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jtxtresult.getText());
            sb.deleteCharAt(jtxtresult.getText().length() -1);
            backsp = sb.toString();
            jtxtresult.setText(backsp);
        }
    }//GEN-LAST:event_jbtnbsActionPerformed

    private void jbtnstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstarActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "*";
    }//GEN-LAST:event_jbtnstarActionPerformed

    private void jbtndig4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_jbtndig4ActionPerformed

    private void jbtndig7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig7ActionPerformed

        EnterNumbers("7");
    }//GEN-LAST:event_jbtndig7ActionPerformed

    private void jbtndig8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_jbtndig8ActionPerformed

    private void jbtndig9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_jbtndig9ActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "+";
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtndig5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_jbtndig5ActionPerformed

    private void jbtndig6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_jbtndig6ActionPerformed

    private void jbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtresult.getText());
        jtxtresult.setText("");
        op = "-";
    }//GEN-LAST:event_jbtnminusActionPerformed

    private void jbtndig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_jbtndig2ActionPerformed

    private void jbtndig3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_jbtndig3ActionPerformed

    private void jbtndig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_jbtndig1ActionPerformed

    private void jbtndig0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndig0ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_jbtndig0ActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        if(! jtxtresult.getText().contains(".")){
            jtxtresult.setText(jtxtresult.getText() + jbtndot.getText());
        }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
       NumEnter2 = Double.parseDouble(jtxtresult.getText());
       if(op == "+"){
           Result = NumEnter1 + NumEnter2;
           jtxtresult.setText(String.valueOf(Result));
       }else if(op == "-"){
           Result = NumEnter1 - NumEnter2;
           jtxtresult.setText(String.valueOf(Result));
       }else if(op == "*"){
           Result = NumEnter1 * NumEnter2;
           jtxtresult.setText(String.valueOf(Result));
       }else if(op == "/"){
           Result = NumEnter1 / NumEnter2;
           jtxtresult.setText(String.valueOf(Result));
       }
    }//GEN-LAST:event_jbtnequalActionPerformed

    private void jtxtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtresultActionPerformed

    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed
        jtxtresult.setText("");
    }//GEN-LAST:event_jbtncActionPerformed

    private void jbtnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnceActionPerformed
        jtxtresult.setText("");
        String fn , sn;
        
        fn = String.valueOf(NumEnter1);
        sn = String.valueOf(NumEnter2);
        fn = "";
        sn = "";
    }//GEN-LAST:event_jbtnceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnbs;
    private javax.swing.JButton jbtnc;
    private javax.swing.JButton jbtnce;
    private javax.swing.JButton jbtndig0;
    private javax.swing.JButton jbtndig1;
    private javax.swing.JButton jbtndig2;
    private javax.swing.JButton jbtndig3;
    private javax.swing.JButton jbtndig4;
    private javax.swing.JButton jbtndig5;
    private javax.swing.JButton jbtndig6;
    private javax.swing.JButton jbtndig7;
    private javax.swing.JButton jbtndig8;
    private javax.swing.JButton jbtndig9;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnpm;
    private javax.swing.JButton jbtnslash;
    private javax.swing.JButton jbtnstar;
    private javax.swing.JTextField jtxtresult;
    // End of variables declaration//GEN-END:variables
}
